version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-file-storage}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        required: false

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      # Superuser credentials
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      # App user credentials
      - APP_USER=${DB_USER:-devops}
      - APP_PASSWORD=${DB_PASSWORD:-password}
      - APP_DB=${DB_NAME:-file_storage}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-devops}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

volumes:
  postgres_data: